using System.Diagnostics;
using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using LifeOS.Application.WeeklyReviews;
using LifeOS.Domain.WeeklyReviews;
using Microsoft.Extensions.Logging;

namespace LifeOS.Infrastructure.WeeklyReviews;

// AI-001: client of POST /v1/weekly-review/interpret on the Python AI service (same service, base URL
// and service key as nutrition estimation: NutritionAiOptions). Sends ONLY the snapshot's figures,
// minimised: weekdays instead of dates, names cut to MaxNameLength, bounded lists; never user ids,
// review ids, dates, zones or tokens. Every failure is a result, never an exception: the service's
// status codes and messages do not leave this class, and neither the figures, the insights nor the
// key is ever logged (only status, latency and the provider/model/prompt identity).
internal sealed class WeeklyReviewInterpreterClient : IWeeklyReviewInterpreter, IDisposable
{
    private const string InterpretPath = "v1/weekly-review/interpret";

    // Request bounds of the service (lifeos_ai/weekly_review/schema.py). Lists are already ordered
    // largest/earliest first by the snapshot, so a cut keeps the most relevant entries; totals are
    // always complete.
    internal const int MaxNameLength = 100;
    internal const int MaxCurrencies = 10;
    internal const int MaxCategories = 12;
    internal const int MaxWorkouts = 28;

    // Strict: numbers must be JSON numbers, names are the service's snake_case.
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower
    };

    private readonly HttpClient? _httpClient;
    private readonly AuthenticationHeaderValue? _authorization;
    private readonly ILogger<WeeklyReviewInterpreterClient> _logger;

    public WeeklyReviewInterpreterClient(HttpClient? httpClient, string? serviceKey, ILogger<WeeklyReviewInterpreterClient> logger)
    {
        if (httpClient is not null && string.IsNullOrWhiteSpace(serviceKey))
        {
            throw new ArgumentException("A configured AI service requires a service key.", nameof(serviceKey));
        }

        _httpClient = httpClient;
        _authorization = httpClient is null ? null : new AuthenticationHeaderValue("Bearer", serviceKey!.Trim());
        _logger = logger;
    }

    public async Task<WeeklyReviewInterpretationResult> InterpretAsync(WeeklyReviewSnapshot snapshot, CancellationToken cancellationToken)
    {
        if (_httpClient is null)
        {
            return WeeklyReviewInterpretationResult.Failed(WeeklyReviewInterpretationFailure.Unavailable);
        }

        var started = Stopwatch.GetTimestamp();

        try
        {
            using var request = new HttpRequestMessage(HttpMethod.Post, InterpretPath)
            {
                Content = JsonContent.Create(ToPayload(snapshot), options: JsonOptions)
            };
            request.Headers.Authorization = _authorization;

            using var response = await _httpClient.SendAsync(request, cancellationToken);

            if (response.StatusCode != HttpStatusCode.OK)
            {
                _logger.LogWarning("Weekly review AI service returned HTTP {StatusCode} after {ElapsedMs} ms.",
                    (int)response.StatusCode, Elapsed(started));

                // 502: the provider answered without valid insights. 422: the service rejected the
                // figures (retrying the same snapshot cannot help). Anything else (503, 500, 401 for a
                // rejected service key, ...) means the service cannot answer right now.
                return WeeklyReviewInterpretationResult.Failed(response.StatusCode is HttpStatusCode.BadGateway or HttpStatusCode.UnprocessableEntity
                    ? WeeklyReviewInterpretationFailure.InvalidOutput
                    : WeeklyReviewInterpretationFailure.Unavailable);
            }

            var body = await response.Content.ReadFromJsonAsync<InterpretResponse>(JsonOptions, cancellationToken);

            if (body is not { OutputVersion: { } version, Provider: { } provider, Model: { } model, PromptVersion: { } prompt, Insights: { Summary: { } summary } insights })
            {
                _logger.LogWarning("Weekly review AI service returned incomplete insights.");
                return WeeklyReviewInterpretationResult.Failed(WeeklyReviewInterpretationFailure.InvalidOutput);
            }

            _logger.LogInformation(
                "Weekly review insights generated by {Provider} {Model} with prompt {PromptVersion} (output v{OutputVersion}) in {ElapsedMs} ms.",
                provider, model, prompt, version, Elapsed(started));

            // Missing lists stay null: the Domain rejects them rather than treating them as empty.
            return WeeklyReviewInterpretationResult.Success(new WeeklyReviewInterpretation(
                version,
                new WeeklyReviewInsightsContent(summary, insights.Wins!, insights.Attention!, insights.Patterns!, insights.NextWeekFocus!),
                new AiGenerationIdentity(provider, model, prompt)));
        }
        catch (Exception exception) when (exception is JsonException or NotSupportedException)
        {
            _logger.LogWarning("Weekly review AI service returned unreadable insights.");
            return WeeklyReviewInterpretationResult.Failed(WeeklyReviewInterpretationFailure.InvalidOutput);
        }
        catch (Exception exception) when (exception is HttpRequestException
            || (exception is TaskCanceledException && !cancellationToken.IsCancellationRequested))
        {
            _logger.LogWarning("Weekly review AI service is unreachable or timed out ({ExceptionType}) after {ElapsedMs} ms.",
                exception.GetType().Name, Elapsed(started));
            return WeeklyReviewInterpretationResult.Failed(WeeklyReviewInterpretationFailure.Unavailable);
        }
    }

    public void Dispose() => _httpClient?.Dispose();

    // The exact external payload (see the service's InterpretWeeklyReviewRequest).
    internal static InterpretRequest ToPayload(WeeklyReviewSnapshot snapshot) => new(
        new FinancePayload(snapshot.Finance.Currencies
            .Take(MaxCurrencies)
            .Select(currency => new CurrencyPayload(
                currency.Currency,
                currency.Expenses,
                currency.Income,
                currency.NetFlow,
                currency.ExpenseCategories.Take(MaxCategories).Select(category => new CategoryPayload(Name(category.Name), category.Amount)).ToList()))
            .ToList()),
        new GymPayload(
            snapshot.Gym.CompletedWorkouts,
            snapshot.Gym.TotalDurationSeconds,
            snapshot.Gym.CompletedSets,
            snapshot.Gym.PrescribedSets,
            snapshot.Gym.Workouts
                .Take(MaxWorkouts)
                .Select(workout => new WorkoutPayload(
                    workout.Date.DayOfWeek.ToString(), Name(workout.WorkoutName), Name(workout.ProgramName),
                    workout.DurationSeconds, workout.CompletedSets, workout.PrescribedSets))
                .ToList()),
        new NutritionPayload(
            snapshot.Nutrition.DaysWithMeals,
            snapshot.Nutrition.MealCount,
            snapshot.Nutrition.AnalyzedMealCount,
            snapshot.Nutrition.FullyAnalyzedDays,
            snapshot.Nutrition.AnalyzedCaloriesKcal,
            snapshot.Nutrition.AnalyzedProteinGrams,
            snapshot.Nutrition.AnalyzedCarbsGrams,
            snapshot.Nutrition.AnalyzedFatGrams,
            snapshot.Nutrition.Days
                .Select(day => new NutritionDayPayload(
                    day.Date.DayOfWeek.ToString(), day.MealCount, day.AnalyzedMealCount, day.CaloriesKcal, day.ProteinGrams, day.CarbsGrams, day.FatGrams))
                .ToList()));

    private static string Name(string name)
    {
        var trimmed = name.Trim();

        return trimmed.Length <= MaxNameLength ? trimmed : trimmed[..MaxNameLength].TrimEnd();
    }

    private static long Elapsed(long started) => (long)Stopwatch.GetElapsedTime(started).TotalMilliseconds;

    internal sealed record InterpretRequest(FinancePayload Finance, GymPayload Gym, NutritionPayload Nutrition);

    internal sealed record FinancePayload(List<CurrencyPayload> Currencies);

    internal sealed record CurrencyPayload(string Currency, decimal Expenses, decimal Income, decimal NetFlow, List<CategoryPayload> ExpenseCategories);

    internal sealed record CategoryPayload(string Name, decimal Amount);

    internal sealed record GymPayload(int CompletedWorkouts, long TotalDurationSeconds, int CompletedSets, int PrescribedSets, List<WorkoutPayload> Workouts);

    internal sealed record WorkoutPayload(string Day, string WorkoutName, string ProgramName, long DurationSeconds, int CompletedSets, int PrescribedSets);

    internal sealed record NutritionPayload(int DaysWithMeals, int MealCount, int AnalyzedMealCount, int FullyAnalyzedDays,
        decimal AnalyzedCaloriesKcal, decimal AnalyzedProteinGrams, decimal AnalyzedCarbsGrams, decimal AnalyzedFatGrams, List<NutritionDayPayload> Days);

    internal sealed record NutritionDayPayload(string Day, int MealCount, int AnalyzedMealCount, decimal CaloriesKcal, decimal ProteinGrams,
        decimal CarbsGrams, decimal FatGrams);

    private sealed record InterpretResponse(int? OutputVersion, string? Provider, string? Model, string? PromptVersion, InsightsPayload? Insights);

    private sealed record InsightsPayload(string? Summary, List<string>? Wins, List<string>? Attention, List<string>? Patterns, List<string>? NextWeekFocus);
}
