using System.Diagnostics;
using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using LifeOS.Application.Memory;
using Microsoft.Extensions.Logging;

namespace LifeOS.Infrastructure.Memory;

// AI-004: client of POST /v1/journal-memory/answer on the Python AI service. Sends the question and the
// retrieved passages only (opaque labels S1..Sn, optional title, occurred-at time, chunk text): never a
// user id, entry id or other journal content. Failures are results; the question, passages, answer
// and key are never logged (only status, counts, latency and the provider/model/prompt identity).
internal sealed class JournalAnswerClient : IJournalAnswerService, IDisposable
{
    private const string AnswerPath = "v1/journal-memory/answer";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower
    };

    private readonly HttpClient? _httpClient;
    private readonly AuthenticationHeaderValue? _authorization;
    private readonly ILogger<JournalAnswerClient> _logger;

    public JournalAnswerClient(HttpClient? httpClient, string? serviceKey, ILogger<JournalAnswerClient> logger)
    {
        if (httpClient is not null && string.IsNullOrWhiteSpace(serviceKey))
        {
            throw new ArgumentException("A configured AI service requires a service key.", nameof(serviceKey));
        }

        _httpClient = httpClient;
        _authorization = httpClient is null ? null : new AuthenticationHeaderValue("Bearer", serviceKey!.Trim());
        _logger = logger;
    }

    public async Task<JournalAnswerResult> AnswerAsync(string question, IReadOnlyList<JournalAnswerSource> sources, CancellationToken cancellationToken)
    {
        if (_httpClient is null)
        {
            return JournalAnswerResult.Failed(JournalMemoryAiFailure.Unavailable);
        }

        var started = Stopwatch.GetTimestamp();

        try
        {
            using var request = new HttpRequestMessage(HttpMethod.Post, AnswerPath)
            {
                Content = JsonContent.Create(ToPayload(question, sources), options: JsonOptions)
            };
            request.Headers.Authorization = _authorization;

            using var response = await _httpClient.SendAsync(request, cancellationToken);

            if (response.StatusCode != HttpStatusCode.OK)
            {
                _logger.LogWarning("Journal answer AI service returned HTTP {StatusCode} for {SourceCount} sources after {ElapsedMs} ms.",
                    (int)response.StatusCode, sources.Count, Elapsed(started));

                return JournalAnswerResult.Failed(response.StatusCode is HttpStatusCode.BadGateway or HttpStatusCode.UnprocessableEntity
                    ? JournalMemoryAiFailure.InvalidOutput
                    : JournalMemoryAiFailure.Unavailable);
            }

            var body = await response.Content.ReadFromJsonAsync<AnswerResponse>(JsonOptions, cancellationToken);

            if (body is not { OutputVersion: 1, Provider: { } provider, Model: { } model, PromptVersion: { } prompt, Result: { Status: { } status, Answer: { } answer, Citations: { } citations } })
            {
                _logger.LogWarning("Journal answer AI service returned an incomplete answer.");
                return JournalAnswerResult.Failed(JournalMemoryAiFailure.InvalidOutput);
            }

            _logger.LogInformation("Journal answer generated by {Provider} {Model} with prompt {PromptVersion} from {SourceCount} sources in {ElapsedMs} ms.",
                provider, model, prompt, sources.Count, Elapsed(started));

            return JournalAnswerResult.Success(new JournalGeneratedAnswer(status, answer, citations, provider, model, prompt));
        }
        catch (Exception exception) when (exception is JsonException or NotSupportedException)
        {
            _logger.LogWarning("Journal answer AI service returned an unreadable answer.");
            return JournalAnswerResult.Failed(JournalMemoryAiFailure.InvalidOutput);
        }
        catch (Exception exception) when (exception is HttpRequestException
            || (exception is TaskCanceledException && !cancellationToken.IsCancellationRequested))
        {
            _logger.LogWarning("Journal answer AI service is unreachable or timed out ({ExceptionType}) after {ElapsedMs} ms.",
                exception.GetType().Name, Elapsed(started));
            return JournalAnswerResult.Failed(JournalMemoryAiFailure.Unavailable);
        }
    }

    public void Dispose() => _httpClient?.Dispose();

    // The exact external payload (see the service's AnswerRequest).
    internal static AnswerRequest ToPayload(string question, IReadOnlyList<JournalAnswerSource> sources) =>
        new(question, sources.Select(source => new SourcePayload(source.Label, source.Title, source.OccurredAtUtc.ToUniversalTime(), source.Text)).ToList());

    private static long Elapsed(long started) => (long)Stopwatch.GetElapsedTime(started).TotalMilliseconds;

    internal sealed record AnswerRequest(string Question, List<SourcePayload> Sources);

    internal sealed record SourcePayload(string Label, string? Title, DateTimeOffset OccurredAt, string Text);

    private sealed record AnswerResponse(int? OutputVersion, string? Provider, string? Model, string? PromptVersion, ResultPayload? Result);

    private sealed record ResultPayload(string? Status, string? Answer, List<string>? Citations);
}
