@LifeOS.Api_HostAddress = http://localhost:5091

GET {{LifeOS.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{LifeOS.Api_HostAddress}}/api/accounts
Content-Type: application/json

{
  "name": "Main account",
  "type": "BankAccount",
  "currency": "EUR"
}

###
