// <auto-generated />
using System;
using LifeOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LifeOSDbContext))]
    [Migration("20261002093445_AddGymWorkoutSessions")]
    partial class AddGymWorkoutSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeOS.Domain.Finance.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Accounts.OpeningBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_of_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_opening_balances_account_id");

                    b.HasIndex("UserId");

                    b.HasIndex("AccountId", "UserId");

                    b.ToTable("opening_balances", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Budgets.MonthlyBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year", "Month", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_monthly_budgets_user_month_currency");

                    b.ToTable("monthly_budgets", null, t =>
                        {
                            t.HasCheckConstraint("ck_monthly_budgets_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_monthly_budgets_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_monthly_budgets_year_month", "year BETWEEN 1 AND 9998 AND month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ParentCategoryId", "UserId");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_parent_not_self", "parent_category_id IS NULL OR parent_category_id <> id");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("DestinationAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_account_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("SourceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_account_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("transaction_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("AccountId", "UserId");

                    b.HasIndex("CategoryId", "UserId");

                    b.HasIndex("DestinationAccountId", "UserId");

                    b.HasIndex("SourceAccountId", "UserId");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_transactions_shape", "(transaction_type IN ('Income', 'Expense') AND account_id IS NOT NULL AND category_id IS NOT NULL AND source_account_id IS NULL AND destination_account_id IS NULL) OR (transaction_type = 'Transfer' AND account_id IS NULL AND category_id IS NULL AND source_account_id IS NOT NULL AND destination_account_id IS NOT NULL AND source_account_id <> destination_account_id)");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateId", "UserId");

                    b.ToTable("workout_blocks", null, t =>
                        {
                            t.HasCheckConstraint("ck_workout_blocks_kind", "kind IN ('Single', 'Superset')");

                            t.HasCheckConstraint("ck_workout_blocks_position", "position >= 1");

                            t.HasCheckConstraint("ck_workout_blocks_rest_seconds", "rest_seconds IS NULL OR rest_seconds BETWEEN 1 AND 3600");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutBlockExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkoutBlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_block_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId", "UserId");

                    b.HasIndex("WorkoutBlockId", "UserId");

                    b.ToTable("workout_block_exercises", null, t =>
                        {
                            t.HasCheckConstraint("ck_workout_block_exercises_position", "position BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("workout_programs", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutSetPrescription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("TargetMaxReps")
                        .HasColumnType("integer")
                        .HasColumnName("target_max_reps");

                    b.Property<int>("TargetMinReps")
                        .HasColumnType("integer")
                        .HasColumnName("target_min_reps");

                    b.Property<Guid>("WorkoutBlockExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_block_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutBlockExerciseId");

                    b.ToTable("workout_set_prescriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_workout_set_prescriptions_position", "position >= 1");

                            t.HasCheckConstraint("ck_workout_set_prescriptions_reps", "target_min_reps >= 1 AND target_max_reps >= target_min_reps AND target_max_reps <= 999");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkoutProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_program_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutProgramId", "UserId");

                    b.ToTable("workout_templates", null, t =>
                        {
                            t.HasCheckConstraint("ck_workout_templates_position", "position >= 1");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Sessions.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("program_name");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkoutName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workout_name");

                    b.Property<Guid?>("WorkoutProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_program_id");

                    b.Property<Guid?>("WorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_workout_sessions_user_in_progress")
                        .HasFilter("status = 'InProgress'");

                    b.HasIndex("WorkoutProgramId");

                    b.HasIndex("WorkoutTemplateId");

                    b.HasIndex("UserId", "StartedAtUtc")
                        .HasDatabaseName("ix_workout_sessions_user_started_at");

                    b.ToTable("workout_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_workout_sessions_completion", "(status = 'InProgress' AND completed_at_utc IS NULL) OR (status = 'Completed' AND completed_at_utc IS NOT NULL AND completed_at_utc >= started_at_utc)");

                            t.HasCheckConstraint("ck_workout_sessions_status", "status IN ('InProgress', 'Completed')");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Sessions.WorkoutSessionBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_workout_session_blocks_session_position");

                    b.HasIndex("WorkoutSessionId", "UserId");

                    b.ToTable("workout_session_blocks", null, t =>
                        {
                            t.HasCheckConstraint("ck_workout_session_blocks_kind", "kind IN ('Single', 'Superset')");

                            t.HasCheckConstraint("ck_workout_session_blocks_position", "position >= 1");

                            t.HasCheckConstraint("ck_workout_session_blocks_rest_seconds", "rest_seconds IS NULL OR rest_seconds BETWEEN 1 AND 3600");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Sessions.WorkoutSessionExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkoutSessionBlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_session_block_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId", "UserId");

                    b.HasIndex("WorkoutSessionBlockId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_workout_session_exercises_block_position");

                    b.HasIndex("WorkoutSessionBlockId", "UserId");

                    b.ToTable("workout_session_exercises", null, t =>
                        {
                            t.HasCheckConstraint("ck_workout_session_exercises_position", "position BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Sessions.WorkoutSessionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActualReps")
                        .HasColumnType("integer")
                        .HasColumnName("actual_reps");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("TargetMaxReps")
                        .HasColumnType("integer")
                        .HasColumnName("target_max_reps");

                    b.Property<int>("TargetMinReps")
                        .HasColumnType("integer")
                        .HasColumnName("target_min_reps");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.Property<Guid>("WorkoutSessionExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_session_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionExerciseId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_workout_session_sets_exercise_position");

                    b.ToTable("workout_session_sets", null, t =>
                        {
                            t.HasCheckConstraint("ck_workout_session_sets_actual", "(completed_at_utc IS NULL AND actual_reps IS NULL AND weight_kg IS NULL) OR (completed_at_utc IS NOT NULL AND actual_reps BETWEEN 1 AND 999 AND (weight_kg IS NULL OR (weight_kg > 0 AND weight_kg <= 1000)))");

                            t.HasCheckConstraint("ck_workout_session_sets_position", "position >= 1");

                            t.HasCheckConstraint("ck_workout_session_sets_target_reps", "target_min_reps >= 1 AND target_max_reps >= target_min_reps AND target_max_reps <= 999");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Users.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EmailAtSignIn")
                        .HasColumnType("text")
                        .HasColumnName("email_at_sign_in");

                    b.Property<DateTimeOffset>("LastSignInAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sign_in_at_utc");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_external_identities_provider_subject");

                    b.ToTable("external_identities", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefaultCurrency")
                        .HasColumnType("character(3)")
                        .HasColumnName("default_currency");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("OnboardingCompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarding_completed_at_utc");

                    b.Property<string>("OnboardingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("onboarding_status");

                    b.Property<DateTimeOffset?>("StarterCategoriesInitializedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starter_categories_initialized_at_utc");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_user_sessions_family_id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_user_sessions_refresh_token_hash");

                    b.HasIndex("UserId");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Accounts.Account", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Accounts.OpeningBalance", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_opening_balances_accounts_account_id_user_id");
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Budgets.MonthlyBudget", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Categories.Category", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.Finance.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_categories_categories_parent_category_id_user_id");
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Transactions.Transaction", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_transactions_accounts_account_id_user_id");

                    b.HasOne("LifeOS.Domain.Finance.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_transactions_categories_category_id_user_id");

                    b.HasOne("LifeOS.Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_transactions_accounts_destination_account_id_user_id");

                    b.HasOne("LifeOS.Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_transactions_accounts_source_account_id_user_id");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Exercises.Exercise", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutBlock", b =>
                {
                    b.HasOne("LifeOS.Domain.Gym.Programs.WorkoutTemplate", null)
                        .WithMany("Blocks")
                        .HasForeignKey("WorkoutTemplateId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_workout_blocks_workout_templates");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutBlockExercise", b =>
                {
                    b.HasOne("LifeOS.Domain.Gym.Exercises.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_workout_block_exercises_exercises");

                    b.HasOne("LifeOS.Domain.Gym.Programs.WorkoutBlock", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutBlockId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_workout_block_exercises_workout_blocks");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutProgram", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutSetPrescription", b =>
                {
                    b.HasOne("LifeOS.Domain.Gym.Programs.WorkoutBlockExercise", null)
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutBlockExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_workout_set_prescriptions_workout_block_exercises");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutTemplate", b =>
                {
                    b.HasOne("LifeOS.Domain.Gym.Programs.WorkoutProgram", null)
                        .WithMany("Workouts")
                        .HasForeignKey("WorkoutProgramId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_workout_templates_workout_programs");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Sessions.WorkoutSession", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.Gym.Programs.WorkoutProgram", null)
                        .WithMany()
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_workout_sessions_workout_programs");

                    b.HasOne("LifeOS.Domain.Gym.Programs.WorkoutTemplate", null)
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_workout_sessions_workout_templates");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Sessions.WorkoutSessionBlock", b =>
                {
                    b.HasOne("LifeOS.Domain.Gym.Sessions.WorkoutSession", null)
                        .WithMany("Blocks")
                        .HasForeignKey("WorkoutSessionId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_workout_session_blocks_workout_sessions");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Sessions.WorkoutSessionExercise", b =>
                {
                    b.HasOne("LifeOS.Domain.Gym.Exercises.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_workout_session_exercises_exercises");

                    b.HasOne("LifeOS.Domain.Gym.Sessions.WorkoutSessionBlock", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSessionBlockId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_workout_session_exercises_workout_session_blocks");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Sessions.WorkoutSessionSet", b =>
                {
                    b.HasOne("LifeOS.Domain.Gym.Sessions.WorkoutSessionExercise", null)
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_workout_session_sets_workout_session_exercises");
                });

            modelBuilder.Entity("LifeOS.Domain.Users.ExternalIdentity", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Users.UserSession", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutBlock", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutBlockExercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutProgram", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Programs.WorkoutTemplate", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Sessions.WorkoutSession", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Sessions.WorkoutSessionBlock", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("LifeOS.Domain.Gym.Sessions.WorkoutSessionExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
