// <auto-generated />
using System;
using LifeOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LifeOSDbContext))]
    [Migration("20261002091023_AddAccountBalanceReconciliation")]
    partial class AddAccountBalanceReconciliation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeOS.Domain.Finance.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Accounts.AccountBalanceAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at_utc");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<decimal>("ObservedBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("observed_balance");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "UserId");

                    b.HasIndex("Id", "AccountId", "UserId");

                    b.HasIndex("UserId", "AccountId", "EffectiveAtUtc")
                        .HasDatabaseName("ix_account_balance_adjustments_user_account_time");

                    b.ToTable("account_balance_adjustments", null, t =>
                        {
                            t.HasCheckConstraint("ck_account_balance_adjustments_nonzero", "amount <> 0");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Accounts.AccountReconciliation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at_utc");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<decimal>("ObservedBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("observed_balance");

                    b.Property<decimal>("PreviousBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("previous_balance");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("AccountId", "UserId", "RequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_account_reconciliations_account_user_request");

                    b.ToTable("account_reconciliations", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Accounts.OpeningBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_of_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_opening_balances_account_id");

                    b.HasIndex("UserId");

                    b.HasIndex("AccountId", "UserId");

                    b.ToTable("opening_balances", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Budgets.MonthlyBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year", "Month", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_monthly_budgets_user_month_currency");

                    b.ToTable("monthly_budgets", null, t =>
                        {
                            t.HasCheckConstraint("ck_monthly_budgets_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_monthly_budgets_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_monthly_budgets_year_month", "year BETWEEN 1 AND 9998 AND month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ParentCategoryId", "UserId");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_parent_not_self", "parent_category_id IS NULL OR parent_category_id <> id");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("DestinationAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_account_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("SourceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_account_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("transaction_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("AccountId", "UserId");

                    b.HasIndex("CategoryId", "UserId");

                    b.HasIndex("DestinationAccountId", "UserId");

                    b.HasIndex("SourceAccountId", "UserId");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_transactions_shape", "(transaction_type IN ('Income', 'Expense') AND account_id IS NOT NULL AND category_id IS NOT NULL AND source_account_id IS NULL AND destination_account_id IS NULL) OR (transaction_type = 'Transfer' AND account_id IS NULL AND category_id IS NULL AND source_account_id IS NOT NULL AND destination_account_id IS NOT NULL AND source_account_id <> destination_account_id)");
                        });
                });

            modelBuilder.Entity("LifeOS.Domain.Users.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EmailAtSignIn")
                        .HasColumnType("text")
                        .HasColumnName("email_at_sign_in");

                    b.Property<DateTimeOffset>("LastSignInAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sign_in_at_utc");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_external_identities_provider_subject");

                    b.ToTable("external_identities", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefaultCurrency")
                        .HasColumnType("character(3)")
                        .HasColumnName("default_currency");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("OnboardingCompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarding_completed_at_utc");

                    b.Property<string>("OnboardingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("onboarding_status");

                    b.Property<DateTimeOffset?>("StarterCategoriesInitializedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starter_categories_initialized_at_utc");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_user_sessions_family_id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_user_sessions_refresh_token_hash");

                    b.HasIndex("UserId");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Accounts.Account", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Accounts.AccountBalanceAdjustment", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_account_balance_adjustments_accounts_account_id_user_id");

                    b.HasOne("LifeOS.Domain.Finance.Accounts.AccountReconciliation", null)
                        .WithMany()
                        .HasForeignKey("Id", "AccountId", "UserId")
                        .HasPrincipalKey("Id", "AccountId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_adjustments_reconciliation_receipt");
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Accounts.AccountReconciliation", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_account_reconciliations_accounts_account_id_user_id");
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Accounts.OpeningBalance", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_opening_balances_accounts_account_id_user_id");
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Budgets.MonthlyBudget", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Categories.Category", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.Finance.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_categories_categories_parent_category_id_user_id");
                });

            modelBuilder.Entity("LifeOS.Domain.Finance.Transactions.Transaction", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_transactions_accounts_account_id_user_id");

                    b.HasOne("LifeOS.Domain.Finance.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_transactions_categories_category_id_user_id");

                    b.HasOne("LifeOS.Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_transactions_accounts_destination_account_id_user_id");

                    b.HasOne("LifeOS.Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_transactions_accounts_source_account_id_user_id");
                });

            modelBuilder.Entity("LifeOS.Domain.Users.ExternalIdentity", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Users.UserSession", b =>
                {
                    b.HasOne("LifeOS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
