namespace LifeOS.Domain.Notifications;

public enum DevicePlatform
{
    Android
}

public enum PushProvider
{
    Fcm
}

public enum DeviceRegistrationStatus
{
    Active,
    Inactive
}

public enum DeviceInactiveReason
{
    PermissionDenied,
    SignedOut,
    TokenInvalid
}

// AUTO-001 §5.2 / §12: "where can this user be reached". One row per (app installation, LifeOS user)
// ownership: when another user signs in on an installation, the previous owner's row becomes
// Inactive and the new owner gets (or reactivates) its own row, so delivery history keeps its owner
// (composite FK from notification_deliveries). At most one row per installation is Active.
//
// Active ⇔ a push token is present, the OS permission is granted and the user is signed in there.
// Inactive rows keep no token. Transitions are atomic statements in the repository; this type
// creates valid rows and defines the input rules.
public sealed class DeviceRegistration
{
    public const int MinInstallationIdLength = 16;
    public const int MaxInstallationIdLength = 64;
    public const int MaxPushTokenLength = 4096;

    private DeviceRegistration(
        Guid id,
        Guid userId,
        string installationId,
        DevicePlatform platform,
        PushProvider pushProvider,
        string? pushToken,
        DeviceRegistrationStatus status,
        DeviceInactiveReason? inactiveReason,
        DateTimeOffset createdAtUtc,
        DateTimeOffset updatedAtUtc,
        DateTimeOffset lastSeenAtUtc)
    {
        Id = id;
        UserId = userId;
        InstallationId = installationId;
        Platform = platform;
        PushProvider = pushProvider;
        PushToken = pushToken;
        Status = status;
        InactiveReason = inactiveReason;
        CreatedAtUtc = createdAtUtc;
        UpdatedAtUtc = updatedAtUtc;
        LastSeenAtUtc = lastSeenAtUtc;
    }

    public Guid Id { get; }

    public Guid UserId { get; }

    // Random id generated by the app per installation (survives sign-outs, lost on reinstall).
    public string InstallationId { get; }

    public DevicePlatform Platform { get; }

    public PushProvider PushProvider { get; }

    // Sensitive: never logged, never returned by an API. Null when Inactive.
    public string? PushToken { get; }

    public DeviceRegistrationStatus Status { get; }

    public DeviceInactiveReason? InactiveReason { get; }

    public DateTimeOffset CreatedAtUtc { get; }

    public DateTimeOffset UpdatedAtUtc { get; }

    // Last registration upsert from the app.
    public DateTimeOffset LastSeenAtUtc { get; }

    // The state an upsert from the app writes: Active with the token when notifications are
    // permitted, otherwise Inactive (PermissionDenied) without a token.
    public static DeviceRegistration Register(
        Guid userId,
        string installationId,
        DevicePlatform platform,
        string? pushToken,
        bool notificationsPermitted,
        DateTimeOffset nowUtc)
    {
        if (userId == Guid.Empty)
        {
            throw new ArgumentException("A valid user id is required.", nameof(userId));
        }

        if (!IsValidInstallationId(installationId))
        {
            throw new ArgumentException("Invalid installation id.", nameof(installationId));
        }

        if (notificationsPermitted ? !IsValidPushToken(pushToken) : pushToken is not null)
        {
            throw new ArgumentException("A push token is required exactly when notifications are permitted.", nameof(pushToken));
        }

        var now = nowUtc.ToUniversalTime();

        return new DeviceRegistration(
            Guid.CreateVersion7(),
            userId,
            installationId,
            platform,
            ProviderFor(platform),
            notificationsPermitted ? pushToken : null,
            notificationsPermitted ? DeviceRegistrationStatus.Active : DeviceRegistrationStatus.Inactive,
            notificationsPermitted ? null : DeviceInactiveReason.PermissionDenied,
            now,
            now,
            now);
    }

    public static PushProvider ProviderFor(DevicePlatform platform) => platform switch
    {
        DevicePlatform.Android => PushProvider.Fcm,
        _ => throw new ArgumentOutOfRangeException(nameof(platform), platform, null)
    };

    // 16–64 characters of [A-Za-z0-9_-] (the app sends a random UUID). The lower bound keeps the id
    // unguessable: registering an installation id takes it over from its previous owner.
    public static bool IsValidInstallationId(string? installationId) =>
        installationId is { Length: >= MinInstallationIdLength and <= MaxInstallationIdLength }
        && installationId.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');

    // 1–4096 visible ASCII characters without spaces (FCM tokens are opaque ASCII strings).
    public static bool IsValidPushToken(string? pushToken) =>
        pushToken is { Length: > 0 and <= MaxPushTokenLength }
        && pushToken.All(character => character is >= '!' and <= '~');
}
